export enum Feature {
  CONTACT_SHOW_EMAIL = "CONTACT_SHOW_EMAIL",
  HEADER_MENU = "HEADER_MENU",
  LOGIN_LOCALDEAL = "LOGIN_LOCALDEAL",
  LOGIN_GOOGLE_OAUTH = "LOGIN_GOOGLE_OAUTH",
  LOGIN_WECHAT_OAUTH = "LOGIN_WECHAT_OAUTH"
}
