export enum Feature {
  CONTACT_SHOW_EMAIL = "CONTACT_SHOW_EMAIL",
  HEADER_MENU = "HEADER_MENU",
  DEAL_LEGACY = "DEAL_LEGACY",
  CREATE_DEAL_DRAFT = "CREATE_DEAL_DRAFT",
  LOGIN_LOCALDEAL = "LOGIN_LOCALDEAL",
  LOGIN_GOOGLE_OAUTH = "LOGIN_GOOGLE_OAUTH",
  LOGIN_WECHAT_OAUTH = "LOGIN_WECHAT_OAUTH",
  USER_PROFILE_IN_HEADER = "USER_PROFILE_IN_HEADER",
  USER_PROFILE_IN_HEADER_MENU = "USER_PROFILE_IN_HEADER_MENU"
}
